# Generated by Django 5.1.4 on 2024-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysismodel",
            name="parameters",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
