# Support the author by using the funding links below
# GitHub Sponsors: https://github.com/sponsors/gabrielclimb
# Buy Me a Coffee: https://buymeacoffee.com/gabrielsoares

github: gabrielclimb
buy_me_a_coffee: gabrielsoares

